Master
maxlintelo/speed-camera pull request #10
Opened 2023-04-10 21:14 UTC by LarsFaase

feedback processed

2023-04-11 10:54 UTC, maxlintelo commented
Alles in de out directory moet worden geignored. Staat ook in de gitignore dus idk hoe het er weer bij is gekomen.

2023-04-11 10:56 UTC, ThomasintAnker requested changes

2023-04-11 10:56 UTC, ThomasintAnker commented on Documentation/RD_SpeedCamera/content/camera.tex
> +    The area over which your camera can take an image is known as the field of view of FOV, the larger the FOV, the more you can see of your sample. If you have a large field of view, you can take mo
Zet het ff in je eigen woorden, is geen moeite. Nu is het gwn van deze site gecopy+paste
https://www.photometrics.com/learn/camera-basics/camera-field-of-view

2023-04-11 10:56 UTC, ThomasintAnker commented on Documentation/RD_SpeedCamera/content/camera.tex
> +    The number of frames a camera records per second is called the frame rate. The frame rate determines how smoothly you play back the images. You use a high frame rate to film fast movements smooth
Reference image in text

2023-04-12 12:33 UTC, ThomasintAnker approved these changes

2023-04-12 12:33 UTC, ThomasintAnker commented on Documentation/RD_SpeedCamera/content/camera.tex
> +\section{Recognizing a car driving down the road requires a camera. Available cameras are compared on the following points:}
Wat is dit kopje, dit is gewoon een volledige zin?

2023-04-12 12:33 UTC, ThomasintAnker commented on Documentation/RD_SpeedCamera/content/camera.tex
> +\section{The different interfaces to communicate with the camera module:}
Wat is dit kopje, dit is gewoon een volledige zin?

2023-04-12 12:33 UTC, ThomasintAnker commented on Documentation/RD_SpeedCamera/content/camera.tex
> +\section{The different camera's}
```suggestion
\section{The different cameras}
```

2023-04-12 15:40 UTC, Nike2002 commented on Documentation/RD_SpeedCamera/content/camera.tex
> +As mentioned in the conclusion, you want to have an FOV that is as small as possible because you want to be able to read a licence plate sharply from a reasonable distance. With the Raspberry Pi HQ c
Leg uit waarom je voor de Raspberry pi gekozen hebt.

2023-04-16 20:09 UTC, maxlintelo approved these changes
Approved for deadline

2023-04-16 20:09 UTC, merged