Design speed recognition
maxlintelo/speed-camera pull request #9
Opened 2023-04-10 11:36 UTC by ThomasintAnker

Added the speed recognition chapter to the design document, please review.

2023-04-10 12:33 UTC, ThomasintAnker commented
Currently adding an appendix for the calculations required for the speed calculation so that will be added somewhere later today/tomorrow

2023-04-12 15:51 UTC, Nike2002 requested changes

2023-04-12 15:51 UTC, Nike2002 commented on Documentation/DSD_SpeedCamera/content/speed_calculation.tex
> +the limited space given in the requirements prevents the use of the camera-only speed measuring method. Furthermore, even
Kan je even uitleggen of je het via de fixed point method gaat doen of via de object tracking. Daar zie ik nog geen verschil tussen.

2023-04-16 17:52 UTC, ThomasintAnker commented on Documentation/DSD_SpeedCamera/content/speed_calculation.tex
> +the limited space given in the requirements prevents the use of the camera-only speed measuring method. Furthermore, even
Staat in het paragraaf eronder

2023-04-16 20:08 UTC, maxlintelo approved these changes
Approved for deadline

2023-04-16 20:08 UTC, merged